INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Ac Ajaccio','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Bastia','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Bordeaux','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Lyon','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Marseille','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Paris Saint Germain','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Rennes','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Saint-Etienne','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Toulouse','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Valenciennes','France', 'Ligue 1');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Arsenal','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Chelsea','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Everton','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Fulham','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Liverpool','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Manchester City','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Manchester united','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Newcastle united','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Tottenham Hotspur','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('West Ham United','Angleterre', 'Premiere League');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Atletic Bilbao','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Atletic Madrid','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Betis Seville','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Deportivo La Corogne','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Espagnol Barcelone','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Fc Barcelone','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Fc Seville','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Malaga','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Real Madrid','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Valence Cf','Espagne', 'Liga Espagnole');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Ac Milan','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('As Roma','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Bologne','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Cagliari','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Fiorentina','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Inter Milan','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Juventus Turin','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Lazio Rome','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Naples','Italie', 'Serie A');
INSERT INTO football_equipe (equipe, pays, championnat) VALUES ('Parme','Italie', 'Serie A');